return {

	-- yyyymmdd
	-- if newer than the user's copy, overwrite ALL of its keys
	-- else just add any that are missing from the local config
	["date"] = 20260929,

	-- Default Spring: 1944 keybinds. They follow Zero-K's defaults (the Zero-K
	-- launcher's players already know them): A is attack-move (fight) and F is
	-- force fire (attack).
	["keybinds"] = {
		{	"togglecammode",	"Ctrl+backspace",},
		{	"togglecammode",	"Shift+backspace",},
		{	"edit_backspace",	"Any+backspace",},
		{	"toggleoverview",	"Ctrl+tab",},
		{	"edit_complete",	"Any+tab",},
		{
			"chatally", 			{"Alt+enter", "Alt+numpad_enter"},
		},
		{
			"chatswitchally", 			{"Alt+enter", "Alt+numpad_enter"},
		},
		{
			"chatall", 			{"Ctrl+enter", "Ctrl+numpad_enter"},
		},
		{
			"chatswitchall", 			{"Ctrl+enter", "Ctrl+numpad_enter"},
		},
		{	"chatspec",	"None"},
		{	"chatswitchspec",	"None"},
		{
			"chat", 			{"Any+enter", "Any+numpad_enter"},
		},
		{
			"edit_return", 			{"Any+enter", "Any+numpad_enter"},
		},
		{	"pause",	"pause",},
		{	"crudemenu",	"esc",},
		{	"exitwindow",	"shift+esc",},
		{	"quitforce",	"Ctrl+Shift+esc",},
		{	"edit_escape",	"Any+escape",},
		{	"speedup",	{ "Any++","Any+=","Any+numpad+"}, },
		{	"slowdown",	{"Any+-","Any+numpad-",}, },
		{	"specteam 9",	"0",},
		{	"specteam 19",	"Ctrl+0",},
		{	"group0",	"Any+0",},
		{	"specteam 0",	"1",},
		{	"specteam 10",	"Ctrl+1",},
		{	"group1",	"Any+1",},
		{	"specteam 1",	"2",},
		{	"specteam 11",	"Ctrl+2",},
		{	"group2",	"Any+2",},
		{	"specteam 2",	"3",},
		{	"specteam 12",	"Ctrl+3",},
		{	"group3",	"Any+3",},
		{	"specteam 3",	"4",},
		{	"specteam 13",	"Ctrl+4",},
		{	"group4",	"Any+4",},
		{	"specteam 4",	"5",},
		{	"specteam 14",	"Ctrl+5",},
		{	"group5",	"Any+5",},
		{	"specteam 5",	"6",},
		{	"specteam 15",	"Ctrl+6",},
		{	"group6",	"Any+6",},
		{	"specteam 6",	"7",},
		{	"specteam 16",	"Ctrl+7",},
		{	"group7",	"Any+7",},
		{	"specteam 7",	"8",},
		{	"specteam 17",	"Ctrl+8",},
		{	"group8",	"Any+8",},
		{	"specteam 8",	"9",},
		{	"specteam 18",	"Ctrl+9",},
		{	"group9",	"Any+9",},
		{	"buildfacing inc",	{"Any+insert", "[", "Shift+[",}, },
		{	"drawinmap",	{
				"Any+\\",
				"Any+`",
				"Any+0xa7",
				"Any+^",
			},
		},
		{	"clearmapmarks", "Alt+`"},
		{	"buildfacing dec",	{"Any+delete", "]","Shift+]",}, },
		{	"attack",	"f",},
		{	"movestate",	"h",},
		{	"firestate",	"n",},
		{	"fakefirestate",	"n",},
		{	"areaattack",	"Alt+a",},
		{	"debug",	"Ctrl+Alt+n",},
		{	"debugcolvol",	"Ctrl+Alt+b",},
		{	"repeat",	"ctrl+r"},
		{	"selfd",	"C+k",},
		{	"manualfire",	"d",},
		{	"reclaim",	"e",},
		{	"fight",	"a",},
		{	"forcestart",	"Alt+f",},
		{	"guard",	"g",},
		{	"gameinfo",	"Ctrl+Alt+i",},
		{	"togglelos",	"Ctrl+l",},
		{	"loadunits",	"l",},
		{	"move",	"m",},
		{	"singlestep",	"Alt+o",},
		{	"patrol",	"p",},
		{	"groupclear",	"Shift+q",},
		{	"repair",	"r",},
		{	"stop",	"s",},
		{	"unloadunits",	"u",},
		{	"pastetext",	"Ctrl+v",},
		{	"wait",	"ctrl+w",},
		{	"buildspacing dec",	"Any+x",},
		{	"buildspacing inc",	"Any+z",},
		{	"edit_delete",	"Any+delete",},
		{	"edit_prev_line",	"Any+up",},
		{	"moveforward",	"Any+up",},
		{	"edit_next_line",	"Any+down",},
		{	"moveback",	"Any+down",},
		{	"edit_end",	"Alt+right",},
		{	"edit_next_word",	"Ctrl+right",},
		{	"edit_next_char",	"Any+right",},
		{	"moveright",	"Any+right",},
		{	"edit_home",	"Alt+left",},
		{	"edit_prev_word",	"Ctrl+left",},
		{	"edit_prev_char",	"Any+left",},
		{	"moveleft",	"Any+left",},
		{	"increaseviewradius",	"home",},
		{	"edit_home",	"Any+home",},
		{	"decreaseviewradius",	"end",},
		{	"edit_end",	"Any+end",},
		{	"moveup",	"Any+pageup",},
		{	"movedown",	"Any+pagedown",},
		{	"showelevation",	"f1",},
		{	"showpathtraversability",	"f2",},
		{	"lastmsgpos",	"f3",},
		{	"showmetalmap",	"None"},
		{	"HideInterface",	"None",},
		{	"hideinterfaceandcursor",	"ctrl+f5",},
		{	"NoSound",	"None",},
		{	"DynamicSky",	"None",},
		{	"createvideo",	"Ctrl+Shift+f10",},
		{	"viewlobby",	"f11",},
		{	"luaui tweakgui",	"C+f11",},
		{	"movefast",	"None"},
		{	"moveslow",	"None"},
		{	"movereset",	"Any+alt"},
		{	"movetilt",	"Any+ctrl"},
		{	"epic_chili_widget_selector_widgetlist_2",	"alt+f11",},
		{	"screenshot png",	"f12",},
		{	"screenshot jpg", "ctrl+f12"},
		{	"settarget",	"t",},
		{	"look",	"b",},
		{	"clearpath",	"c",},
		{	"select AllMap++_ClearSelection_SelectAll+",	"ctrl+a",},
		{	"select PrevSelection+_Not_RelativeHealth_30+_ClearSelection_SelectAll+",	"ctrl+e",},
		{	"select AllMap+_Not_Builder_Not_Building+_ClearSelection_SelectAll+",	"ctrl+f",},
		{	"select PrevSelection+_Idle+_ClearSelection_SelectAll+",	"ctrl+i",},
		{	"select AllMap+_Not_Builder_Not_Building_Not_Transport_Aircraft_Radar+_ClearSelection_SelectAll+",	"ctrl+s",},
		{	"select AllMap+_Not_Builder_Not_Building_Transport_Aircraft+_ClearSelection_SelectAll+",	"ctrl+t",},
		{	"select Visible+_InPrevSel+_ClearSelection_SelectAll+",	"ctrl+x",},
		{	"select AllMap+_InPrevSel+_ClearSelection_SelectAll+",	"ctrl+z",},
		{	"exitwindow",	"s+escape",},
		{	"crudesubmenu",	"f10"},
		{	"epic_chili_pro_console_enableconsole", "f8"},
	},
}
